### ISSUE TITLE
ITV not working on ITV Hub

### ISSUE THREAD

**Issue by bwguy** [hoshsadiq/bravia-youview-player-launchers#17]
Great work getting these apps but my postcode doesn't save on ITV Hub so it doesn't let me watch any ITV catch-up, only the others such as ITV2, 3, 4, Be I can watch as these are not regional.

**Comment by hoshsadiq** [comment]
This is likely not something I can help with. If the url itv hub loads and all other functions work, its likely an issue with ITV Hub.

I can try and investigate if you enable the YouView, then open ITV Hub from the YouView app. It may be that they've released a new version on a different URL.

**Comment by bwguy** [comment]
So I bought a little aerial to be able to setup youview (I only use satellite) and it works no problem.  The app uses the postcode you enter into youview.    When disabling youview, again it won't let me watch ITV.  When I compare your app to another ITV Hub app, you don't have any permissions for location.

**Comment by hoshsadiq** [comment]
The apps I have here requires YouView to be enabled. It simply does what the YouView app does but directly as an APK that can be put on your home screen.

Please post set up adb logcat and then open ITV Hub from the YouView app, and post the logcat here. Might wanna make sure your post code isn't in the output if it's there (search with and without space). But please change it to something else rather than remove it.

**Comment by bwguy** [comment]
I cant really keep YouView enabled as it disables my Satellite.  The aerial signal in my area is terrible hence why I use Sat instead.

As ITV Hub is not working for me, I'll use STV hub instead (Even though I live in Wales).  I've put a Glasgow postcode into STV and that works and stays there unlike the ITV Hub.

**Comment by hoshsadiq** [comment]
Without the logs from YouView I can't really do anything, but I'm glad you've found a workaround!
