### ISSUE TITLE
ITV hub not working on Android 9

### ISSUE THREAD

**Issue by rubavinagre** [hoshsadiq/bravia-youview-player-launchers#23]
Hello!

I just installed the ITV hub on my Mi 4s TV, no issues until I try to open it. It closes all of a sudden after I open it.
I know maybe it’s not intended for other TVs other than Sony but as OS is the same I thought it should work.
I cannot find this app working anywhere else so any help would be much appreciated.

Best,
Ruben

**Comment by hoshsadiq** [comment]
Extremely unlikely to work outside of Sony TVs. This just utilises YouView app and bypasses what YouView provides, thus YouView app is required. I suppose it is in theory possible run the apps in a webview instead of using YouView, but that's goes beyond my skill in Android development, and is also beyond the scope of this project.

**Comment by rubavinagre** [comment]
Understood. Didn’t know the logic behind it.
Thanks you very much for your reply.
